### ISSUE TITLE
Please upgrade glob version to latest version to fix security CWE-772

### ISSUE THREAD

**Issue by lhyfcs** [archiverjs/archiver-utils#172]
The version glob@8.1.0 is use module inflight, this module do not update for 7 years, in order to fix the security issue CWE-772 need to upgrade glob version to 10.3.10, please help to upgrade.

**Comment by mysteron** [comment]
👍🏻

**Comment by AlisherAmonulloev** [comment]
@ctalkington would you please check this?

**Comment by timbset** [comment]
Hello @ctalkington ! Could you pay an attention to the problem please? It's very important for us. I see that renovate bot tried to update a version in the PR https://github.com/archiverjs/archiver-utils/pull/145, but tests were failed. It's OK because glob stopped supporting Node v12 starting with glob v9 due to [their changelog](https://github.com/isaacs/node-glob/blob/main/changelog.md#90). So you can replace v12 with v20 in your CI calmly.
